version: "3.9"
services:
  codepay:
    container_name: "codepay"
    build:
      dockerfile: Dockerfile
      context: ./app
    ports:
      - "3000:3000"
  codepay_api:
    container_name: "codepay_api"
    build:
      dockerfile: Dockerfile
      context: ./api
    ports:
      - "8000:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock