name: Sync to Hugging Face Hub
on:
  push:
    branches: [main]
    
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          lfs: true

      - name: Push to Hugging Face Hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          HF_USERNAME: mattmajestic
          SPACE_NAME: web3bms
          SUPABASE_URL: ${{ secrets.SB_URL }}
          SUPABASE_KEY: ${{ secrets.SB_TOKEN }}
        run: |
          # Configure Supabase environment variables
          echo "SUPABASE_URL=$SUPABASE_URL" >> $GITHUB_ENV
          echo "SUPABASE_KEY=$SUPABASE_KEY" >> $GITHUB_ENV

          # Push to Hugging Face Hub
          git push https://$HF_USERNAME:$HF_TOKEN@huggingface.co/spaces/$HF_USERNAME/$SPACE_NAME main
