name: Publish Docker Image to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: |
          docker login -u mattmajestic -p ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and Push to Docker Hub
        run: |
          docker build -t mattmajestic/web3cms:latest .
          docker push mattmajestic/web3cms:latest
