[theme]
base="light"
font="monospace"

[browser]
gatherUsageStats = true

[global]

# Default: false
disableWatchdogWarning = false

# Default: false
disableWidgetStateDuplicationWarning = false

# Default: true
showWarningOnDirectExecution = true

[client]

# Default: true
caching = true

# Default: true
displayEnabled = true

# Default: true
showErrorDetails = true

toolbarMode = "developer"

[runner]

# Default: true
magicEnabled = true

# Default: false
installTracer = false

# Default: true
fixMatplotlib = true

# Default: true
postScriptGC = true

# Default: true
fastReruns = true

enforceSerializableSessionState = false